### PR TITLE
Updated project generator to support mini2Dx 2.0

### PR DESCRIPTION
**Pull request by augustozanellato**

### CODE REVIEW

**Comment by tomcashman** [comment]
A few changes are needed:

- [x] Change mini2Dx/LibGDX Extensions to just 'mini2Dx Extensions'
- [x] Box2d, bullet and box2dlights need to be removed as options since they are Libgdx specific and won't work on consoles
- [x] When it can't connect to Github, the generator should be able to generate projects for 1.9.10 and 2.0.0-alpha.3 by default (currently it still shows 1.3.0-rc.2 from a long time ago :P)

I'll tag the mini2Dx fork of gdx-ai soon

**Comment by augustozanellato** [comment]
Fixed!

**Review by tomcashman — CHANGES_REQUESTED** [review]
One more issue found :P

Need to update the "3rd party extensions" window to say "mini2Dx extensions" and also remove all the existing extensions listed since they are for libgdx

**Comment by augustozanellato** [comment]
Fixed!

**Review by tomcashman — APPROVED** [review]

**Pull request merged**
